# Generated by Django 4.1 on 2022-08-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="body",
            new_name="content",
        ),
    ]
